#!/bin/bash
dir=$( cat ~/.config/noise-selector/dir )

mkdir ~/.config/noise-selector

if [ $# -eq 0 ]
then
    if [ -z "$dir" ]
    then
        echo "Music/" > ~/.config/noise-selector/dir
        dir=$( cat ~/.config/noise-selector/dir )
    fi
    echo "stop"
    ls "$dir" --format=single-column | grep "mp3$\|opus$\|ogg"

else
    if [ x"$@" = x"stop" ]
    then
        killall ffplay
    fi
    coproc ( ffplay -nodisp -loop 0 -loglevel quiet "$dir""$@" > /dev/null 2>&1 )
fi
