#!/bin/bash
if [ $# -eq 0 ]
then
    echo "stop"
    ls ~/Music/"[SKRD!!!-129] V.A. - Polska Ja Wersyja W Byciu Sobą Najbardziej Przeszkadza Nam Kodeks Karny"/ --format=single-column | grep "mp3$\|opus$\|ogg"
else
    if [ x"$@" = x"stop" ]
    then
        killall ffplay
    fi
    coproc ( ffplay -nodisp -loop 0 -loglevel quiet ~/Music/\[SKRD\!\!\!-129\]\ V.A.\ -\ Polska\ Ja\ Wersyja\ W\ Byciu\ Sobą\ Najbardziej\ Przeszkadza\ Nam\ Kodeks\ Karny/"$@" > /dev/null 2>&1 )
fi
